// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eqhopqxxvojzimunrdet.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVxaG9wcXh4dm9qemltdW5yZGV0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzYzMTYwMDUsImV4cCI6MjA1MTg5MjAwNX0.d7dBpzbd8W74J4l8C2pErJ50-cfQVSMCn0PWlYgGb0k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);